# H1B Visa Sql Analysis

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:mahin%40123@localhost:3306/h1b_project")

## Analysis 1 — Top Sponsoring Employers
### Why?
Companies that file the most applications are strong targets for H1B job seekers.

In [2]:
query1 = """
SELECT EMPLOYER_NAME, COUNT(*) AS total_filings
FROM h1b_clean
GROUP BY EMPLOYER_NAME
ORDER BY total_filings DESC
LIMIT 10;
"""

top_employers = pd.read_sql(query1, engine)
top_employers

                            EMPLOYER_NAME  total_filings
0                 AMAZON.COM SERVICES LLC          14604
1  COGNIZANT TECHNOLOGY SOLUTIONS US CORP          11437
2                  ERNST & YOUNG U.S. LLP          10035
3       TATA CONSULTANCY SERVICES LIMITED           9705
4                   MICROSOFT CORPORATION           9492
5                              GOOGLE LLC           9089
6                         INFOSYS LIMITED           5943
7                         HCL AMERICA INC           3981
8               WAL-MART ASSOCIATES, INC.           3934
9                              APPLE INC.           3814

## Analysis 2 — Highest Paying Job Roles
### Why?
Understanding which job roles offer the highest average salaries helps students choose career paths with stronger earning potential and better sponsorship opportunities.

### Business Value:
Applicants can prioritize high-value roles such as Data Science, Cloud Engineering, AI, and Cybersecurity.

In [3]:
query2 = """
SELECT JOB_TITLE, ROUND(AVG(ANNUAL_SALARY),2) AS avg_salary
FROM h1b_clean
GROUP BY JOB_TITLE
HAVING COUNT(*) >= 20
ORDER BY avg_salary DESC
LIMIT 10;
"""

pd.read_sql(query2, engine)

                           JOB_TITLE  avg_salary
0  PULMONARY CRITICAL CARE PHYSICIAN   432541.14
1        INTERVENTIONAL CARDIOLOGIST   400111.77
2                      PULMONOLOGIST   398893.22
3                       CARDIOLOGIST   375188.44
4                   ANESTHESIOLOGIST   372592.78
5  PULMONARY/CRITICAL CARE PHYSICIAN   360310.79
6                 GASTROENTEROLOGIST   359852.80
7                   NEUROHOSPITALIST   342363.69
8       EMERGENCY MEDICINE PHYSICIAN   340997.60
9                    GENERAL SURGEON   340592.94

## Analysis 3 — Best States for H1B Opportunities
### Why?
Some states have significantly more H1B job opportunities due to the concentration of technology companies, consulting firms, and large enterprises.

### Business Value:
Applicants can target states with higher demand to improve their chances of finding sponsorship opportunities.

In [4]:
query3 = """
SELECT WORKSITE_STATE, COUNT(*) AS total_jobs
FROM h1b_clean
GROUP BY WORKSITE_STATE
ORDER BY total_jobs DESC
LIMIT 10;
"""

pd.read_sql(query3, engine)

  WORKSITE_STATE  total_jobs
0             CA      101921
1             TX       83680
2             NY       45118
3             WA       34044
4             NJ       29635
5             IL       23644
6             GA       22572
7             NC       20971
8             MA       20684
9             FL       17856

## Analysis 4 — Job Concentration by State
### Why?
Different states specialize in different job markets. Identifying which roles are most common in each state helps applicants align their job search geographically.

### Business Value:
Students can apply strategically by matching their skills to the strongest job markets in each state.

In [5]:
query4 = """
SELECT WORKSITE_STATE, JOB_TITLE, COUNT(*) AS total
FROM h1b_clean
GROUP BY WORKSITE_STATE, JOB_TITLE
ORDER BY total DESC
LIMIT 20;
"""

pd.read_sql(query4, engine)

   WORKSITE_STATE                         JOB_TITLE  total
0              CA                 SOFTWARE ENGINEER  10520
1              TX                SOFTWARE DEVELOPER   7230
2              TX                 SOFTWARE ENGINEER   5068
3              WA                 SOFTWARE ENGINEER   4404
4              WA              SOFTWARE ENGINEERING   2718
5              CA          SENIOR SOFTWARE ENGINEER   2177
6              NJ                SOFTWARE DEVELOPER   2044
7              NY                 SOFTWARE ENGINEER   1945
8              WA  SOFTWARE DEVELOPMENT ENGINEER II   1788
9              NY                         ASSOCIATE   1507
10             NJ                 SOFTWARE ENGINEER   1465
11             GA                SOFTWARE DEVELOPER   1412
12             NC                SOFTWARE DEVELOPER   1219
13             CA                SOFTWARE DEVELOPER   1183
14             IL                SOFTWARE DEVELOPER   1173
15             VA                SOFTWARE DEVELOPER   1143
16             CA  SOFTWARE DEVELOPMENT ENGINEER II   1133
17             GA                 SOFTWARE ENGINEER   1121
18             TX                     DATA ENGINEER   1104
19             TX          SENIOR SOFTWARE ENGINEER   1032

## Analysis 5 — Top Industries Hiring H1B Workers
### Why?
Identifying industries with the highest number of filings helps applicants focus on sectors that actively sponsor international talent.

In [6]:
query5 = """
SELECT NAICS_CODE, COUNT(*) AS total_filings
FROM h1b_clean
GROUP BY NAICS_CODE
ORDER BY total_filings DESC
LIMIT 10;
"""

pd.read_sql(query5, engine)

   NAICS_CODE  total_filings
0      541511         141367
1      541512          40936
2      611310          31078
3      513210          14161
4       45411          13462
5      541211          11328
6       54151          11232
7      518210          11003
8      541330           9579
9      622110           8880

## Analysis 6 — Average Salary by State
### Why?
Comparing salaries across states helps applicants balance opportunity with compensation.

In [7]:
query6 = """
SELECT WORKSITE_STATE,
ROUND(AVG(ANNUAL_SALARY),2) AS avg_salary
FROM h1b_clean
GROUP BY WORKSITE_STATE
ORDER BY avg_salary DESC
LIMIT 10;
"""

pd.read_sql(query6, engine)

  WORKSITE_STATE  avg_salary
0             WV   163435.95
1             CA   152739.61
2             WA   151975.61
3             NY   137718.53
4             ME   131527.50
5             MA   121439.25
6             DC   119992.27
7             NJ   118755.53
8             OR   118675.65
9             DE   117824.94

## Analysis 7 — Visa Class Distribution
### Why?
This shows which visa categories dominate the dataset and confirms focus on H1B-related filings.

In [8]:
query7 = """
SELECT VISA_CLASS, COUNT(*) AS total
FROM h1b_clean
GROUP BY VISA_CLASS
ORDER BY total DESC;
"""

pd.read_sql(query7, engine)

        VISA_CLASS   total
0             H-1B  545128
1   E-3 AUSTRALIAN   10315
2      H-1B1 CHILE    2280
3  H-1B1 SINGAPORE    1511

## Analysis 8 — Full-Time Position Analysis
### Why?
Most H1B roles are full-time. This confirms the type of employment commonly offered.

In [9]:
query8 = """
SELECT FULL_TIME_POSITION, COUNT(*) AS total
FROM h1b_clean
GROUP BY FULL_TIME_POSITION;
"""

pd.read_sql(query8, engine)

  FULL_TIME_POSITION   total
0                  Y  549237
1                  N    9997

## Analysis 9 — Quarterly Filing Trend
### Why?
Quarterly trends help identify seasonal patterns in H1B filings during FY2024.

In [10]:
query9 = """
SELECT quarter, COUNT(*) AS total_filings
FROM h1b_clean
GROUP BY quarter
ORDER BY quarter;
"""

pd.read_sql(query9, engine)

  quarter  total_filings
0      Q1          99316
1      Q2         123480
2      Q3         215897
3      Q4         120541

## Analysis 10 — Highest Paying Employers
### Why?
Applicants can target companies that consistently offer higher salaries.

In [11]:
query10 = """
SELECT EMPLOYER_NAME,
ROUND(AVG(ANNUAL_SALARY),2) AS avg_salary,
COUNT(*) AS total_jobs
FROM h1b_clean
GROUP BY EMPLOYER_NAME
HAVING COUNT(*) >= 20
ORDER BY avg_salary DESC
LIMIT 10;
"""

pd.read_sql(query10, engine)

                          EMPLOYER_NAME  avg_salary  total_jobs
0             OSF MULTI-SPECIALTY GROUP   367231.93          56
1            AURORA MEDICAL GROUP, INC.   352535.35          30
2  ANTHROPIC, PBC D/B/A ANTHROPIC, INC.   326000.00          35
3                      ALLEGHENY CLINIC   316886.63          30
4  APOGEE MEDICAL GROUP, DELAWARE, INC.   314327.29          21
5              OU HEALTH PARTNERS, INC.   313190.91          22
6                      OPENAI OPCO, LLC   310797.23          81
7                  KIRKLAND & ELLIS LLP   309335.54          68
8            WEIL, GOTSHAL & MANGES LLP   309193.55          31
9             VIDANT MEDICAL GROUP, LLC   309174.20          20